version: '3'
services:
  server: 
    build:
      context: ./server
    volumes: 
      - ./server:/app

  client:
    build:
      context: ./client
    volumes: 
      - ./client:/app
    stdin_open: true
    tty: true
